---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
#  - ./cilium/ks.yaml                   # Larry: adopt the default cni, flannel, of OMNI kubernetes.
#  - ./coredns/ks.yaml                  # Larry: adopt omni's default coredns.
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
