echo " bindings --- " &&  kubectl get bindings -A | grep -i flannel
echo " componentstatuses --- " &&  kubectl get componentstatuses -A | grep -i flannel
echo " configmaps --- " &&  kubectl get configmaps -A | grep -i flannel
echo " endpoints --- " &&  kubectl get endpoints -A | grep -i flannel
echo " events --- " &&  kubectl get events -A | grep -i flannel
echo " limitranges --- " &&  kubectl get limitranges -A | grep -i flannel
echo " namespaces --- " &&  kubectl get namespaces -A | grep -i flannel
echo " nodes --- " &&  kubectl get nodes -A | grep -i flannel
echo " persistentvolumeclaims --- " &&  kubectl get persistentvolumeclaims -A | grep -i flannel
echo " persistentvolumes --- " &&  kubectl get persistentvolumes -A | grep -i flannel
echo " pods --- " &&  kubectl get pods -A | grep -i flannel
echo " podtemplates --- " &&  kubectl get podtemplates -A | grep -i flannel
echo " replicationcontrollers --- " &&  kubectl get replicationcontrollers -A | grep -i flannel
echo " resourcequotas --- " &&  kubectl get resourcequotas -A | grep -i flannel
echo " secrets --- " &&  kubectl get secrets -A | grep -i flannel
echo " serviceaccounts --- " &&  kubectl get serviceaccounts -A | grep -i flannel
echo " services --- " &&  kubectl get services -A | grep -i flannel
echo " mutatingwebhookconfigurations --- " &&  kubectl get mutatingwebhookconfigurations -A | grep -i flannel
echo " validatingadmissionpolicies --- " &&  kubectl get validatingadmissionpolicies -A | grep -i flannel
echo " validatingadmissionpolicybindings --- " &&  kubectl get validatingadmissionpolicybindings -A | grep -i flannel
echo " validatingwebhookconfigurations --- " &&  kubectl get validatingwebhookconfigurations -A | grep -i flannel
echo " customresourcedefinitions --- " &&  kubectl get customresourcedefinitions -A | grep -i flannel
echo " apiservices --- " &&  kubectl get apiservices -A | grep -i flannel
echo " controllerrevisions --- " &&  kubectl get controllerrevisions -A | grep -i flannel
echo " daemonsets --- " &&  kubectl get daemonsets -A | grep -i flannel
echo " deployments --- " &&  kubectl get deployments -A | grep -i flannel
echo " replicasets --- " &&  kubectl get replicasets -A | grep -i flannel
echo " statefulsets --- " &&  kubectl get statefulsets -A | grep -i flannel
echo " selfsubjectreviews --- " &&  kubectl get selfsubjectreviews -A | grep -i flannel
echo " tokenreviews --- " &&  kubectl get tokenreviews -A | grep -i flannel
echo " localsubjectaccessreviews --- " &&  kubectl get localsubjectaccessreviews -A | grep -i flannel
echo " selfsubjectaccessreviews --- " &&  kubectl get selfsubjectaccessreviews -A | grep -i flannel
echo " selfsubjectrulesreviews --- " &&  kubectl get selfsubjectrulesreviews -A | grep -i flannel
echo " subjectaccessreviews --- " &&  kubectl get subjectaccessreviews -A | grep -i flannel
echo " horizontalpodautoscalers --- " &&  kubectl get horizontalpodautoscalers -A | grep -i flannel
echo " cronjobs --- " &&  kubectl get cronjobs -A | grep -i flannel
echo " jobs --- " &&  kubectl get jobs -A | grep -i flannel
echo " certificatesigningrequests --- " &&  kubectl get certificatesigningrequests -A | grep -i flannel
echo " leases --- " &&  kubectl get leases -A | grep -i flannel
echo " endpointslices --- " &&  kubectl get endpointslices -A | grep -i flannel
echo " events --- " &&  kubectl get events -A | grep -i flannel
echo " flowschemas --- " &&  kubectl get flowschemas -A | grep -i flannel
echo " prioritylevelconfigurations --- " &&  kubectl get prioritylevelconfigurations -A | grep -i flannel
echo " ingressclasses --- " &&  kubectl get ingressclasses -A | grep -i flannel
echo " ingresses --- " &&  kubectl get ingresses -A | grep -i flannel
echo " ipaddresses --- " &&  kubectl get ipaddresses -A | grep -i flannel
echo " networkpolicies --- " &&  kubectl get networkpolicies -A | grep -i flannel
echo " servicecidrs --- " &&  kubectl get servicecidrs -A | grep -i flannel
echo " runtimeclasses --- " &&  kubectl get runtimeclasses -A | grep -i flannel
echo " poddisruptionbudgets --- " &&  kubectl get poddisruptionbudgets -A | grep -i flannel
echo " clusterrolebindings --- " &&  kubectl get clusterrolebindings -A | grep -i flannel
echo " clusterroles --- " &&  kubectl get clusterroles -A | grep -i flannel
echo " rolebindings --- " &&  kubectl get rolebindings -A | grep -i flannel
echo " roles --- " &&  kubectl get roles -A | grep -i flannel
echo " deviceclasses --- " &&  kubectl get deviceclasses -A | grep -i flannel
echo " resourceclaims --- " &&  kubectl get resourceclaims -A | grep -i flannel
echo " resourceclaimtemplates --- " &&  kubectl get resourceclaimtemplates -A | grep -i flannel
echo " resourceslices --- " &&  kubectl get resourceslices -A | grep -i flannel
echo " priorityclasses --- " &&  kubectl get priorityclasses -A | grep -i flannel
echo " csidrivers --- " &&  kubectl get csidrivers -A | grep -i flannel
echo " csinodes --- " &&  kubectl get csinodes -A | grep -i flannel
echo " csistoragecapacities --- " &&  kubectl get csistoragecapacities -A | grep -i flannel
echo " storageclasses --- " &&  kubectl get storageclasses -A | grep -i flannel
echo " volumeattachments --- " &&  kubectl get volumeattachments -A | grep -i flannel
echo " volumeattributesclasses --- " &&  kubectl get volumeattributesclasses -A | grep -i flannel
