echo " bindings --- " &&  kubectl get bindings -A | grep -i enp
echo " componentstatuses --- " &&  kubectl get componentstatuses -A | grep -i enp
echo " configmaps --- " &&  kubectl get configmaps -A | grep -i enp
echo " endpoints --- " &&  kubectl get endpoints -A | grep -i enp
echo " events --- " &&  kubectl get events -A | grep -i enp
echo " limitranges --- " &&  kubectl get limitranges -A | grep -i enp
echo " namespaces --- " &&  kubectl get namespaces -A | grep -i enp
echo " nodes --- " &&  kubectl get nodes -A | grep -i enp
echo " persistentvolumeclaims --- " &&  kubectl get persistentvolumeclaims -A | grep -i enp
echo " persistentvolumes --- " &&  kubectl get persistentvolumes -A | grep -i enp
echo " pods --- " &&  kubectl get pods -A | grep -i enp
echo " podtemplates --- " &&  kubectl get podtemplates -A | grep -i enp
echo " replicationcontrollers --- " &&  kubectl get replicationcontrollers -A | grep -i enp
echo " resourcequotas --- " &&  kubectl get resourcequotas -A | grep -i enp
echo " secrets --- " &&  kubectl get secrets -A | grep -i enp
echo " serviceaccounts --- " &&  kubectl get serviceaccounts -A | grep -i enp
echo " services --- " &&  kubectl get services -A | grep -i enp
echo " challenges --- " &&  kubectl get challenges -A | grep -i enp
echo " orders --- " &&  kubectl get orders -A | grep -i enp
echo " mutatingwebhookconfigurations --- " &&  kubectl get mutatingwebhookconfigurations -A | grep -i enp
echo " validatingadmissionpolicies --- " &&  kubectl get validatingadmissionpolicies -A | grep -i enp
echo " validatingadmissionpolicybindings --- " &&  kubectl get validatingadmissionpolicybindings -A | grep -i enp
echo " validatingwebhookconfigurations --- " &&  kubectl get validatingwebhookconfigurations -A | grep -i enp
echo " customresourcedefinitions --- " &&  kubectl get customresourcedefinitions -A | grep -i enp
echo " apiservices --- " &&  kubectl get apiservices -A | grep -i enp
echo " controllerrevisions --- " &&  kubectl get controllerrevisions -A | grep -i enp
echo " daemonsets --- " &&  kubectl get daemonsets -A | grep -i enp
echo " deployments --- " &&  kubectl get deployments -A | grep -i enp
echo " replicasets --- " &&  kubectl get replicasets -A | grep -i enp
echo " statefulsets --- " &&  kubectl get statefulsets -A | grep -i enp
echo " selfsubjectreviews --- " &&  kubectl get selfsubjectreviews -A | grep -i enp
echo " tokenreviews --- " &&  kubectl get tokenreviews -A | grep -i enp
echo " localsubjectaccessreviews --- " &&  kubectl get localsubjectaccessreviews -A | grep -i enp
echo " selfsubjectaccessreviews --- " &&  kubectl get selfsubjectaccessreviews -A | grep -i enp
echo " selfsubjectrulesreviews --- " &&  kubectl get selfsubjectrulesreviews -A | grep -i enp
echo " subjectaccessreviews --- " &&  kubectl get subjectaccessreviews -A | grep -i enp
echo " horizontalpodautoscalers --- " &&  kubectl get horizontalpodautoscalers -A | grep -i enp
echo " cronjobs --- " &&  kubectl get cronjobs -A | grep -i enp
echo " jobs --- " &&  kubectl get jobs -A | grep -i enp
echo " certificaterequests --- " &&  kubectl get certificaterequests -A | grep -i enp
echo " certificates --- " &&  kubectl get certificates -A | grep -i enp
echo " clusterissuers --- " &&  kubectl get clusterissuers -A | grep -i enp
echo " issuers --- " &&  kubectl get issuers -A | grep -i enp
echo " certificatesigningrequests --- " &&  kubectl get certificatesigningrequests -A | grep -i enp
echo " ciliumcidrgroups --- " &&  kubectl get ciliumcidrgroups -A | grep -i enp
echo " ciliumclusterwidenetworkpolicies --- " &&  kubectl get ciliumclusterwidenetworkpolicies -A | grep -i enp
echo " ciliumendpoints --- " &&  kubectl get ciliumendpoints -A | grep -i enp
echo " ciliumidentities --- " &&  kubectl get ciliumidentities -A | grep -i enp
echo " ciliuml2announcementpolicies --- " &&  kubectl get ciliuml2announcementpolicies -A | grep -i enp
echo " ciliumloadbalancerippools --- " &&  kubectl get ciliumloadbalancerippools -A | grep -i enp
echo " ciliumlocalredirectpolicies --- " &&  kubectl get ciliumlocalredirectpolicies -A | grep -i enp
echo " ciliumnetworkpolicies --- " &&  kubectl get ciliumnetworkpolicies -A | grep -i enp
echo " ciliumnodeconfigs --- " &&  kubectl get ciliumnodeconfigs -A | grep -i enp
echo " ciliumnodes --- " &&  kubectl get ciliumnodes -A | grep -i enp
echo " ciliumpodippools --- " &&  kubectl get ciliumpodippools -A | grep -i enp
echo " leases --- " &&  kubectl get leases -A | grep -i enp
echo " endpointslices --- " &&  kubectl get endpointslices -A | grep -i enp
echo " events --- " &&  kubectl get events -A | grep -i enp
echo " dnsendpoints --- " &&  kubectl get dnsendpoints -A | grep -i enp
echo " flowschemas --- " &&  kubectl get flowschemas -A | grep -i enp
echo " prioritylevelconfigurations --- " &&  kubectl get prioritylevelconfigurations -A | grep -i enp
echo " fluxinstances --- " &&  kubectl get fluxinstances -A | grep -i enp
echo " fluxreports --- " &&  kubectl get fluxreports -A | grep -i enp
echo " resourcesetinputproviders --- " &&  kubectl get resourcesetinputproviders -A | grep -i enp
echo " resourcesets --- " &&  kubectl get resourcesets -A | grep -i enp
echo " backends --- " &&  kubectl get backends -A | grep -i enp
echo " backendtrafficpolicies --- " &&  kubectl get backendtrafficpolicies -A | grep -i enp
echo " clienttrafficpolicies --- " &&  kubectl get clienttrafficpolicies -A | grep -i enp
echo " envoyextensionpolicies --- " &&  kubectl get envoyextensionpolicies -A | grep -i enp
echo " envoypatchpolicies --- " &&  kubectl get envoypatchpolicies -A | grep -i enp
echo " envoyproxies --- " &&  kubectl get envoyproxies -A | grep -i enp
echo " httproutefilters --- " &&  kubectl get httproutefilters -A | grep -i enp
echo " securitypolicies --- " &&  kubectl get securitypolicies -A | grep -i enp
echo " backendtlspolicies --- " &&  kubectl get backendtlspolicies -A | grep -i enp
echo " gatewayclasses --- " &&  kubectl get gatewayclasses -A | grep -i enp
echo " gateways --- " &&  kubectl get gateways -A | grep -i enp
echo " grpcroutes --- " &&  kubectl get grpcroutes -A | grep -i enp
echo " httproutes --- " &&  kubectl get httproutes -A | grep -i enp
echo " referencegrants --- " &&  kubectl get referencegrants -A | grep -i enp
echo " tcproutes --- " &&  kubectl get tcproutes -A | grep -i enp
echo " tlsroutes --- " &&  kubectl get tlsroutes -A | grep -i enp
echo " udproutes --- " &&  kubectl get udproutes -A | grep -i enp
echo " xbackendtrafficpolicies --- " &&  kubectl get xbackendtrafficpolicies -A | grep -i enp
echo " xlistenersets --- " &&  kubectl get xlistenersets -A | grep -i enp
echo " xmeshes --- " &&  kubectl get xmeshes -A | grep -i enp
echo " helmreleases --- " &&  kubectl get helmreleases -A | grep -i enp
echo " kustomizations --- " &&  kubectl get kustomizations -A | grep -i enp
echo " nodes --- " &&  kubectl get nodes -A | grep -i enp
echo " pods --- " &&  kubectl get pods -A | grep -i enp
echo " alertmanagerconfigs --- " &&  kubectl get alertmanagerconfigs -A | grep -i enp
echo " alertmanagers --- " &&  kubectl get alertmanagers -A | grep -i enp
echo " podmonitors --- " &&  kubectl get podmonitors -A | grep -i enp
echo " probes --- " &&  kubectl get probes -A | grep -i enp
echo " prometheusagents --- " &&  kubectl get prometheusagents -A | grep -i enp
echo " prometheuses --- " &&  kubectl get prometheuses -A | grep -i enp
echo " prometheusrules --- " &&  kubectl get prometheusrules -A | grep -i enp
echo " scrapeconfigs --- " &&  kubectl get scrapeconfigs -A | grep -i enp
echo " servicemonitors --- " &&  kubectl get servicemonitors -A | grep -i enp
echo " thanosrulers --- " &&  kubectl get thanosrulers -A | grep -i enp
echo " ingressclasses --- " &&  kubectl get ingressclasses -A | grep -i enp
echo " ingresses --- " &&  kubectl get ingresses -A | grep -i enp
echo " ipaddresses --- " &&  kubectl get ipaddresses -A | grep -i enp
echo " networkpolicies --- " &&  kubectl get networkpolicies -A | grep -i enp
echo " servicecidrs --- " &&  kubectl get servicecidrs -A | grep -i enp
echo " runtimeclasses --- " &&  kubectl get runtimeclasses -A | grep -i enp
echo " alerts --- " &&  kubectl get alerts -A | grep -i enp
echo " providers --- " &&  kubectl get providers -A | grep -i enp
echo " receivers --- " &&  kubectl get receivers -A | grep -i enp
echo " poddisruptionbudgets --- " &&  kubectl get poddisruptionbudgets -A | grep -i enp
echo " clusterrolebindings --- " &&  kubectl get clusterrolebindings -A | grep -i enp
echo " clusterroles --- " &&  kubectl get clusterroles -A | grep -i enp
echo " rolebindings --- " &&  kubectl get rolebindings -A | grep -i enp
echo " roles --- " &&  kubectl get roles -A | grep -i enp
echo " deviceclasses --- " &&  kubectl get deviceclasses -A | grep -i enp
echo " resourceclaims --- " &&  kubectl get resourceclaims -A | grep -i enp
echo " resourceclaimtemplates --- " &&  kubectl get resourceclaimtemplates -A | grep -i enp
echo " resourceslices --- " &&  kubectl get resourceslices -A | grep -i enp
echo " priorityclasses --- " &&  kubectl get priorityclasses -A | grep -i enp
echo " buckets --- " &&  kubectl get buckets -A | grep -i enp
echo " externalartifacts --- " &&  kubectl get externalartifacts -A | grep -i enp
echo " gitrepositories --- " &&  kubectl get gitrepositories -A | grep -i enp
echo " helmcharts --- " &&  kubectl get helmcharts -A | grep -i enp
echo " helmrepositories --- " &&  kubectl get helmrepositories -A | grep -i enp
echo " ocirepositories --- " &&  kubectl get ocirepositories -A | grep -i enp
echo " csidrivers --- " &&  kubectl get csidrivers -A | grep -i enp
echo " csinodes --- " &&  kubectl get csinodes -A | grep -i enp
echo " csistoragecapacities --- " &&  kubectl get csistoragecapacities -A | grep -i enp
echo " storageclasses --- " &&  kubectl get storageclasses -A | grep -i enp
echo " volumeattachments --- " &&  kubectl get volumeattachments -A | grep -i enp
echo " volumeattributesclasses --- " &&  kubectl get volumeattributesclasses -A | grep -i enp
