apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ePtQOkDeBu1xm9vqwClU3RB2b5MztEk4FfPe+qqQ4GpkasSa1F7I1Q==,iv:blCPqUlenuqqbeS6R0hagVqLBpu48cZAdpmOBlBMwgA=,tag:cQ08AkUcNOpA47gLhDjLbQ==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTkgyQm91alByTXBWZGNE
        aGh0ZDNZcGVPTDM2US9VbXgxT0hhNjV1bFY4CnVPQ1RXRDlsNjRaTW54QXk4aDM4
        R3N6c2RFSjc0MzRMOHc0V056UXJISDgKLS0tIHJsdmZBWW9JMEZvQW5Ickdvbndz
        THg3dkZsckV1cUhqc1pGVkdYSENxTUkKhzivv2ZI0dmw6De3neYWne9PZPRdA3uR
        7HTRV4G+mcFIe334QCYCjhT7/xQdcf8ses5GvOo4Zhw9myPoeq473Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T18:12:20Z"
  mac: ENC[AES256_GCM,data:u8qlFH+wtWZCwkGmqGus8Ef6FqKlvpokP/2s8fpve/I+HqRLpXR6P/oAVUvKh7yKUp9s1Wub18ZeqSK6z4dbOaB0xsV3H8ECLfnwt6BUIdj1Mo432DmugEaB7wbaridR1s6vDXlEf3nF8V9CR+DJXNYOfnfcZePNms1EQZuem5Y=,iv:g0DAx8LM5xNvWkzk3tqE+VQve59quEpV5Fxx1FYUHWc=,tag:jxNB7Cs+e2Foo+9Lt+xPJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
