apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sdHA7EGQUop1NJ9LU7pO5W9sgZtrVS5Iy848b2APR2VAzbQJykCoTA==,iv:HilfSGJZ9wdU3ARPcBAD1cjpg2mk9/CakTfw2LPUHG8=,tag:DU8P2Y/fHlponp6/kINQag==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMXlGa3BNaDFJM2NwQ2pj
        WXhUajY0SHRmNHV5a3RWUWNuaGtjczFPK1I0Ckw0N3l2c2JrL3ZFRkhZUEp6azFw
        NnhXWXNEWC8rRlFtYTF6UVBvRXNzOW8KLS0tIFJJREFVWmhhdFlPWkF1eFU4aFpa
        VS9NdFY4Y3d3YlE3bEE5K3NmOU4wTmsK7Dq48/GcNWywxkenWItzdH6HpdUMTQg+
        g3MADjms+kYWNMG/3Ydnr9nwGnfyOSltjFTHS2ADE7U+yU22U522zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T14:41:12Z"
  mac: ENC[AES256_GCM,data:yhOdiW1ek5hrX5YMX/pM4CoAXXFcqus4PaJoKBL6SY0n0/6i0O6XHx4e2b9Uw+nP9nzWA+3vPoeYvj7naNXZ/fOP5eFjTyUUKnDWMKhZ7QwyOVx0zkjzGr1lkiN7VOM/26zUP1glL+V5waI7JejOIXwzj0/NcDONWhN6xa90FsY=,iv:31CobXH+WA8/oUdqpaWF482Xotcz5kvqFQyi5LU5590=,tag:gm9O+FqcKMx6+fH251aU0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
