apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7oC3ui8M2Yz3Ykb0guFTRNZePubkQsLJzdXVEvazIV6jvM7C7uB+sg==,iv:ipw0Dsyt8tYT8wZMBggvQShkQyYwHkVDZtCUJm0if24=,tag:keuWcvI+2S0T5VcsR3nzyg==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTjJPTkpTa3h4Snh4QTIz
        cU4yVnJKVU1GR05CcHM1dWNIcVYxMGFmZ1VBCk5MZzdYK0c5b25ndUxEY1ZDQ1hp
        ajhnem82QkFrMkYwbU5RT3g0YlBpVWsKLS0tIERwS2JHTyt3V3kwYWI0aWFybFBL
        MmhQcGNPWjgwNHkwNVV4Ui91cm5lVWsKM43QrA9Qzw3SIBIqXxW7NPTWJANv9wmp
        2E/WQR6QbPfoEyxeYDccu3F4TZGeNADWQ3T8Bl7duj29p0fSvy3HCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T14:28:41Z"
  mac: ENC[AES256_GCM,data:GjbfrVTeCGwS0UmaWXSL9+0dkKyht5edmKbHQr1SW63SqJRGmc5zHAbh7NGGyWOa9P+0CMdZSrG2kjDLa+0lxKWNT+KCWqPmOFl9PvYGziiSbl14LTSjE4OcHuD4TzgXWfyrJOdK2LgTOcPbWgmrOCAqZdB83EtuVRV3tQACBUQ=,iv:bix5Qeg7MlFUYS5gbT3twoVh/S/U2iaJFNtg2k1EE4E=,tag:9EN45DkCGoIvURtiIM9zQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
