apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bQW1qncUOkoEiQ==,iv:DxtbunMwnFhxqtrmQgNwh7xWdrPKkCfMJalLmp6QmRw=,tag:ayiFSspKv3h5uYd4a0nf/g==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvejdGb0JZZGozY2l4a21m
        WmxGNDVNNU13WVFhaEhYWWhPek1yZmplOERjCkJiRlZ0dEJQalR2QjB1WnlBUGwv
        dzhvWmlXT2lwWmhVVmRvOTc0YVIxNE0KLS0tIGJldWFabWJhNHp1dEtOOW9LYkxC
        MnNVMnhBeXZJbjNHa3JnaXlBSHB3OFEKDKYMC2lt2XLyKlcscSY0qUP9CAvlgCpt
        wXTGmGur/dGAYJyvw+vTuVOVk0ccRQYBr4jTHajYvoIuodvNm7qrNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T14:25:03Z"
  mac: ENC[AES256_GCM,data:W7H1h2OTkHgLJKX79ENukQMkZpm0fTXBv9tbzi7beAp44vtL0KXF+kBJAHfIlLVvic8LgRpE+p3uJqznIXGpiGg5/wkxYcBP7HRaT0rQ9RKDSzaUfhn9easC8WY7gq68xLCdZbjyyoB3OskUuUMY+oClGV7sYn9ZHP87vYtQl1Y=,iv:CErXnAb3N5zqk+7HatP1YWa6MET6RjJFfSIyZpzxXiM=,tag:wwX2uWi4PRcxQpAiqi3/3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
