apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nfqbWRLw8j/qqA==,iv:3U0XpNnhyReNBpMwarTHoUFcwXj50p6B0vm4vEILrMk=,tag:UN+/clnl4LZ78nAJb5gC5g==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU2Rnci95VEZrSEoyc1JL
        cm42dDhuQzIzQ3VOZFR4bW1zSTMxUXlpSDM0CksybHFmWlA4TFQwaTlwcmFCdGZD
        eG5RRW1zQ25nbGZJc1pyWEhBTm5pcEEKLS0tIGE5aDJCdlV1dWp1NFF5eFM0djhX
        OUtrWjcyZE5KV01YcWFveGhid1R3a0kK8tjkVAuA+HCwNo/WsfFS79Q9HLMcgfrA
        /X1sYOUZHpS2G+N4CN5DITuW1OtKYgZXDuy8yoqpAG0QlZMaGd+1oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T16:14:07Z"
  mac: ENC[AES256_GCM,data:cgYZv5YcQ44vw2SNEkm5LxQwNAGdgTJO7x1ty9VzStLkK+fCEnsSTfzxSDmEKEnntmp2IiF7/NZ3pxS4DTuo/lV8RNXIw5S9Ir/uCz5Kruzvn2BDw/NPPkrRIEu+TUHZxC0MsuUvi/JadYoQ++Rc6C8o2SfMKzRINtHXxPpj0ck=,iv:MEx8Ua571wypj4VjKYf+3DdhNSkg6flh4FXR7B+a4Ck=,tag:WOQBzDNuiykA06NZbj3J2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
