apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:S/d29QUlSz3OCw==,iv:q7EBDOGmaxYWsCe+HAv1Q1YQTw8Vqwwm0/cudjdRrbQ=,tag:FyGa2YX2Y2c8dBB2ZRtMQg==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaU95bDBqN09rKzRIWi9R
        SjFIbUN3bGswb3F1YWoxdnpYMnJnS0duTjE0CkZYa2dCZ1MxZmprYUIwSDJaaFZW
        K1hhM00xanorZmVidVc2RU0rL01HUG8KLS0tIG10cnBSVnVleWVxcUJKNUhOV2pP
        ejR5b3h2M3hMa0RBV1RxWlNGeXpBdHMKmVPVHST1CXxEy3iSo07YbxcVbKJiCeAX
        WjMEDOjTyC739odUp5/v9Jmu16KSH332khZ9aS3YyYZUn5wPJKcJIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T15:40:18Z"
  mac: ENC[AES256_GCM,data:88qKGSZKKGjHfq/z6iwwXIP4fMuHuW0SLF4Tyf+v6IKwKNsuZeiwDnOEUm1OaZDwMVAAcUKep7t/PvE3sVyzarh9JqIeHc1rfb3UjitKZLgMkN39AIlGRs0C2DXnqbPCjCAwBvjPtc3FGI7Y90ipgbgGZ6kwAN3PcUcKifchMGk=,iv:WyF7B7nP1bsGy8mHt+UQXXibO2Wy7iFBVq5FMPiIRBs=,tag:PubmPpKzau3FR4zm8wm15g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
