apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:1mNGs0+XyrsmJVctC8caujlghqsFOCg0qi2x2NtN2yw=,iv:ZiG1kOBFD+Jj6Y7AS00l2ypxsFEn+pcOpgZqmfimIlU=,tag:9O7vqCYyuB+U/PS2JNNtkg==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcyt4R0JER3RETWRUQWR1
        ankzMnhNVUZtdERvMTJSY0cvYUpJSmRYRlEwCnFsejlxSHdnY2JVRytMUjE1MWhD
        SlNBQkx2YjRIY0JWS2N3NXNKd0V3V2MKLS0tIFp0NTMvRnQ0dWhMbUxLSC9kTWVs
        cUp2bHZYbGdJdVlXS1dMMncyVDVlTW8K9cjZWJRGOGbC9VgOGl7zyeBmKZYt03GS
        vJw2I6FO0GHp8c4Ww+CNEp9MZpMnEDAPFt96Mqz+tazI7IkVDbrkVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T16:33:32Z"
  mac: ENC[AES256_GCM,data:x/vvVs7MzHFSoKvl0ohHQN/H9P8SBJdJ/SicGENNRnRc9Xq5aR9h5LATztbbIgUgHQy0GyoqBlckt2DXBp1IcX1fU8Ypz9Tl8BiukTF09kNsv0k3xvEhM20awgVmYP1vP3tfSSC8VYiwCX9M1QNP5XGpQp9LCaetXb51E7v4/fA=,iv:k8AbVGP8v5n6kbYehBH5sHM8myWxocEVPyTpwbkq/QY=,tag:Tg+jDc5px1pZuoWH5gb6PA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
