apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:32m86/dFc002OFApXkm4aVUvHOZKNqhaNeY7rlqJo8U=,iv:zBTLm50g+S3HSp/SVVw5SoGtOrwWz0O5CCpB3L5RMhQ=,tag:fyH35HOJGZXJH1XM1QMyTw==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2STZtZklZdFBRNGtpQ0Zv
        QVdSa3JjREdudVhCV3NUWU1wT2FiWWQwdERVCllwK1ZlVWdFZkVCMVZ3VkM1dWlE
        bHZEd3lxYkpkN1J2bUpiNlhHSkllUjQKLS0tIEVoSW80ODBKR0lMWDZkZlBOUkxK
        ZFU2dmthY0xkN2M0cXNFL2M3eGo4bW8KSEyp3v2uFfyo9LjJHGwxhC15xotG3mju
        KTmWPz7uDpEhbpN786+cgoBRsIoWB9j4xLHBu4BdXaibzLCpcgM0Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T15:38:32Z"
  mac: ENC[AES256_GCM,data:T7TkjZUuOs9Pc55oMyfD77zCADc3tp2IpJbml75OSPOwNcCv6OTod1R9CIILav+S6zZ5NUQXrgnkkmO1X1apoDmyge17F8F19AaSOgeE4ec9SGi9QgbetDt71frmNFa8KDADMirsBaxHzFG85W8t+d99/swCpXSRXoY4kywpOyM=,iv:6/BVG5XzoBDine9Z+1vz5LeFUdlW6YTo6WlXsHM+Bho=,tag:piYtY6NR1vX2/1MOm3VgYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
