apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nPwwEp/hQ+y6TGuDmBiua/MJ1Lb3K35KAeQl5LGdiBY=,iv:dHa6j1n7uM226r8FPSU7y0FWm/bwNVVoRCFCO2g5UWM=,tag:yk3s4eSA3jtND/mlNrUqAw==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSm9kOXdoRThJTy9RRmhP
        RlRKa043YVRnNzNKRTc0SnZwa2pscTIza2tNCncvRG53ajNXWEZkdUVyY2p4emVT
        WHd2ZkxseWx4UXBvckNFZTQzOEJpN28KLS0tIExMdWZFVXp2OVBoaUNWZnRVNURG
        NGpGT1lrL3pCQ3VQNy9MOERsWVFnN0EK9xfrAAH7pX3hzK7ZpN8mb9fmgJ//zEAJ
        m30N19XA9b8q3p882/T4S3YI8xgsBHEOEl7dW8TST3UDGUspKonrYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T09:57:27Z"
  mac: ENC[AES256_GCM,data:BYxofpmIxlf7NOvQFuLOuB9BXAGOSAdnoslmuTrUB2rmoMWq2fflmLWJGtHtzhFGsYia6zIZXCzmNeq9qe7E1GqyykmV7yqN4U0bcxtGXD72Ox6U3KlDZoG02WSktzxfhYrmhWOnY4yyO19AGH4Lzgx2uDfPpsHc36PXJYNIsWI=,iv:yJ+0CqfwpSUIe9hzXwRP0sNgI4eAnp9AloE952QmE18=,tag:scRz94X6tFjuXhfJlqjZ4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
