---
# -- API Token for Cloudflared default lan tunnel token
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-default-lan-token
  namespace: network
stringData:
  token: eyJhIjoiNjU4NWE4ZTUyNWNjZGFlZDI1MzU1NmY4NWEzM2Y3MzYiLCJ0IjoiYTg2NGE1OWMtOTJhOS00OTI2LTkyN2ItYjU4YTc4NTNmYTYyIiwicyI6Ik1UbG1OVFV5WkdZdE5ERmxOQzAwWlRReUxXSXpOakl0Wm1OallUSmlZelU0WlRCaSJ9
