apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni-k8s.janncot.duckdns.org
    name: jcom-k9
contexts:
  - context:
      cluster: jcom-k9
      namespace: default
      user: jcom-k9-ferry133@gmail.com
    name: jcom-k9
current-context: jcom-k9
users:
- name: jcom-k9-ferry133@gmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.janncot.com/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:k9
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
