apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni-k8s.janncot.com
    name: jcom-t2
contexts:
  - context:
      cluster: jcom-t2
      namespace: default
      user: jcom-t2-ferry133@gmail.com
    name: jcom-t2
current-context: jcom-t2
users:
- name: jcom-t2-ferry133@gmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.janncot.com/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:t2
      command: kubectl
      env: null
      provideClusterInfo: false
