apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:msy/ZvLgV6LMdNOjF0yItm/lfkHufuYnsL81ZnkRp6po8vZD7dayI09eIDkIHPKOQZvMiSmi5YUjKbZNBYvnvkz/PvM7G3KFH4tQerIMrbxWUWPEH540SnLionAHNrzh51RjkdSDjsDUVo5lsbdvd9NPb2LhnqVRgpj782v8nDgMOdrKgxXRsYUDcIzv0xdZblCATMEKlHlOkemX0p+8FPXnjR+z4SFPAfIEigsJZLVpu+QU,iv:dtWYEuVMXJAp5S5aNd+9+/vaeNnSkJ3UKZMZxWjASgM=,tag:Zjy++fbx4j5W1VOf6jTLXA==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbTNYV3JRTFMyM3hRK2hv
        RTV0K3FqdjhMM01kTWUydTJSYis3NjBLbkJZCmNuNi9EZDhMOEg3bElKZzArNS9B
        UnlpUmdRSnlqWTF6aWx5OW1aTFNKdkkKLS0tICtKVzFwZitsWkFjRjl4aFdTZ1Nw
        anArTzRWOEZuTzFDWHZOelBuMzdqWFEKb7qIfqMhqtUFi6FucUBVPAnyN5f2uZLQ
        WqEGLBM/rqLd/QEUol7Nb8JppNnUTKFlmCOQb+9LrRBCGfaJnGuYvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T14:25:04Z"
  mac: ENC[AES256_GCM,data:nG6kQElk1SdFgjcwYEHws/VzKHhEZha8PLsp2vYk8Nvmkqwx1NwhEwjYY9zrLtjcXo/7kp/tKTcCZZTtMchhzvJu4HOUl15JJQU9YB/sWPM4qp+GSjW2Q1R1P+MRPcPBTPz6Mz83e/JPJvN+HmjbTS2TzWe25zmNHTYH0spenPI=,iv:3v2LAy0Az6NhxH/G7eKye/J7YeG4y7KoyGMmGigyFTg=,tag:VRJvT8964WvBvp4AZ88DcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
