apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1PudyuvZJGwEtidvmfb1bCs3kbsfvOahMk1nV3iHeMVcXhdYiogISdA5TGZaUucBp6rqSiMF/ewe+Pho4QSPP9ho3uA5bi/ZwMf05e17JlS9rgNY1wxpQblzc3HzBPYLO3TDntsMCiDT0XrpMQaoC7ZFVxkUASUG+AqbCZQyk9i8byuaXu9Pivp0jJogHe9xOXf+x5t5nMrCzXW7UWoz0wr2IN/68Ax58/fp86oOdPTQErpw,iv:IFzbtPhMHz524VBKb3ViWhU65qYkhvLTuviKTlkajrw=,tag:mk7uxq/1pHt7nB5620N7ew==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY0JUZDdPb0EvcEQwOVhK
        d0dGN2UyR1BKOEpUT2J1aXlRQ0R3RnFjMDN3CnhUMmVJQXpqeFF2K1hxc3Z5OCs1
        c0xrajh1OG5TVUN6L2lOZ3pPZC85eHcKLS0tIGFMRTlqbVR4N1JiT0ZsWTBaNFVi
        N244Mm1pT004QTZmWVdEd1V0MG1jS0UK7VuXEMdE3uHqu7+00Y+A1O/uPK8cDvZ1
        KH0DlYw5ma1R9QXkgN9ZFpkntecqSTJMS1hrYDsTPid4dvSmAzAWMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T18:12:20Z"
  mac: ENC[AES256_GCM,data:u1zRO3wSknNCebw7P5hsPIx7epvYYOcEmouYmys85KRsXmB6H4LndzI7Jt38S38Grl/Ow5zWq36TieUI3EUEHQ5CXNib4REZsDNA+FLGRIc5kXsMO27QL+InIhJLGUnXPHz1DWWeOZgteBGKDGk3LTyvFvSMNE/bxvDS0xdBTJI=,iv:TfB/RIyCFdbaQN6V/5bM/mrPaa8WJpX13NynwA8Mrrw=,tag:07Aou/3l5pO1o5ycvO+QXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
