apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:FenZHFhf5hD0fu0L9FtvEE5nFDwyGefGL8Q8zKCBAEFp/C0tHSVWnUnyfrDrvMJpd9J8DUoptcMccA4LbTU2llhMx5f1f2RDsLfiN82zdqvcQmGUYdYi82OyrFnGlbfFZGlxy2ajFmN3UtJx2lgU4t/ReYmq5cwhPg2uFw5lRRrJy88FZnnQrAAPJIg5TOQDzkUx8j7+wCWqf/XrOtjm6wsHWUgkXeutDr+4rG6KybB0nLJa,iv:VPMsA8XUxyqH2ze/qF+VW37ZOZZifnb13XQVDc92faI=,tag:yioCDWnSctsLr0W1yWzOOQ==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTXRwbHl0elNtRS9VaVJF
        bDhHck1YZm4wLzdOS013SUU2bHVieWxWaVQwCm02MnlyYTVNUlJ1bHlQLzVoZjVp
        RUR2S3k3UndUVmdPcEloUVZIVzFuRjQKLS0tIGVGOWdXdVRsREpjbUxQbU5OWkZW
        V0dUOU9Sa0VzdnFkcEVHM0toQW0vMWcKEn31rdOuN3BxSjH0+B7e3gxxq2ddOYxG
        Txpf3V00YcV2TakDzTlCEd2YYgOAriMcQZA8sIHAay1ygxAWYRKGyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T15:38:33Z"
  mac: ENC[AES256_GCM,data:mmmB7zioGUTr/ZJ8DKu15ztEKXHspxxG0ipSOoOJQfVcbAFrqB/OVkF3AWfxTB4dey/sSoliYpQ5wBEApfl01Vka3C6W4aV0Ex/ourKLwI3vcbcjIBBDLsulmqOEY49J3Vc1bSFQ0//6pINGCniuqG2tAl1pcXNRDSOcq/pkcq8=,iv:ldL4jD4bHQ090UKsSrtv6uyfdaQHyEwIqgFREych7r4=,tag:Mpnk6C/RQHK/GSGpT8DVYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
