apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZlUOtPSWwxgtY+R38QGgzzwq3zP72mhW9JTOxRXkb/mR6JwHRshByQ==,iv:ZMde2PFawEZFONKJWeUgg6pcI+Z+0iV6Yd9/sZg89Uk=,tag:twU4vnflPZDFVf4+v6f3LQ==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdlNPSmQ0b3ZMSFFKRDFr
        RGZnSm54Z0JUaU1JNHRSQkRYRlRNL096bm1BCkthQmFUUmNqbjRlTnVpNVEvSThO
        ZDdnM3duN05GeGJMSGZtdWJrOEo0TFUKLS0tIG00TE9ycEFXQVVyZDB2WGI1RVVa
        R2FkTTAvcm93ck9hL09HNUVVUVlEVlUKBGbAw/g04AqsHta/K0QHrVXRrttwF7BO
        d4+kCb496ClYoISBsV9ENFN+67+tYBDu/G24kP8YmYGzqA/+BCwIFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T15:38:33Z"
  mac: ENC[AES256_GCM,data:SygLqL2filhdf0afvpXQ9jYNcoc8JICjURErj2i2acrSyzutxyK06+XrFb54f0uon0+kyt7i4eaMY0rX1vj3Kwn6asO7u82iiguhKj9ykguz57Qhf8sWHYqnR2nkPLoHalsLnx2PdNeLgHhXYdnZjYDT3smPHFBFaK2v7pnmDok=,iv:nE4Npa79+mt9iOxGiJaGJnGu7LX4wCNiSGC6meu0nsE=,tag:Q1JZW1wXSefuaqzzrcgKyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
