apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UwnAdPHHQHKaCA1fp5/xbJNt9qdvZuwVnnEubPxOQFI9z/UDGQx6sg==,iv:F/VJ4GpDus4XikWGIiyxU6TaGmCqEr0dTEC37kJPJAI=,tag:gt5r3UowoBVHpzCm5iWcWQ==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVDlRQW9ieGpmbVh4dnNl
        Tk5LYlpFQitObkVPWW5iWE9kS2FJb3BXQURzClExV1RFRjBQVHVwVHZuVDFTaDhR
        NkxLK2YxRXdxaDVOdW5aSlpRMjBWOTgKLS0tIDZpcHZZYUtkQk9QZmM5L3lVZ0Nk
        cVk0dlQ0SWxVNFA2b090QUNkR0FVWXcK8rlQqckW3diwzj9oK/TXJX1uII4s0r2Q
        22TS9VwieOEMQT8YASEOzwbtMiFeyiINYSDRdEUAS9Jxucz9W1Zkfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T16:33:32Z"
  mac: ENC[AES256_GCM,data:F+VzTKhfhlNQVd11Rmo9Csnv+9FEu50/6U5jWYNBGvJd4Q0z28dX6fiUP7nbEqx3UW5qqRiGWXOLhCeUMUMJLTyXIZQsZ8bDKTclTN5zLhVcyW4Ke9MVGAMpGThx/MKAYqDkGDjxGTo/JSJlwabwppj++N32iZnoz6OSASFNXFI=,iv:FAThFt7kW58zBn21VhzmKNzYgmEXYQm/n0f5j+Xsh9A=,tag:7csuIwx4PTLG7Su0o2cQ3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
