apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:TYhb0ZFl61aXxdqdQ3BWjExGigwwhx+7U0TqGC854QRdQ4HmYG+H4A==,iv:sVgtcRD9TS3rQIZtu8iZAeiHiI/pcmEWpX67bztNuJc=,tag:SEJLhdXWuiIkzDzWZxh2Yw==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMStWT2FKOHA0WnZyQjBQ
        ZGVNVythVnVUb1ZKcFV2aHZCRXlRU1FXMVVBClllVFQ5SzJNNGNhajlxd2NkRUt1
        b0tmb2VGRHBISXNXUHorczZJbTFyclUKLS0tIE8wQXppQWw1RjR2eGdvNVBQTnl0
        UHNObXVJU3JncFB4Tjc0bElZT2ZnMFkKndYigd/WfS4Kr253ZaduNuXNZ83+93QS
        Cf6sxp/dQaNHAmkrrS4FVZ0fofomWP7Lujg8Ht0EocHEAjy+lwNsqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T14:25:03Z"
  mac: ENC[AES256_GCM,data:wnMZnZsmZFW+oal0lnkW5EpnxdETO+OKA5oYrTr+aag6zY5i13/wwE8hti2Wx+xc1Eqa6vLyyfvR4RiEuZn09HffAdXDFb7JVxVUqCspJSOf7uiXD/VY0U/1ELNPhvJiet3FHZfz/sUOOINXL+4ukmNOhRIZvL14s+E/ra3yAbQ=,iv:LRgeYlXzWHgPYD7QvoddGv/RlJORxTpTvNftEg13mDI=,tag:rhjtreGnngyr5bJ09o5aug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
